#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'chef-server'
cookbook 'curl'
cookbook 'firefox', {:github => 'lakim/chef-firefox'}
cookbook 'gae-cookbook', {:github => 'ikame/gae-cookbook'}
cookbook 'git'
cookbook 'jenkins'
cookbook 'java', {:github => 'socrata-cookbooks/java'}
cookbook 'locale'
cookbook 'memcached' 
cookbook 'mongodb', {:github => 'edelight/chef-mongodb'}
cookbook 'monit', {:github => 'apsoto/monit'}
cookbook 'mysql', {:github => 'opscode-cookbooks/mysql'} 
cookbook 'nginx'
cookbook 'nodejs', {:github => 'mdxp/nodejs-cookbook'}
cookbook 'npm', {:github => 'balbeko/chef-npm'}
cookbook 'openssl'
cookbook 'php'
cookbook 'phppgadmin', {:github => 'plexus/chef-phppgadmin'}
cookbook 'postgresql', {:github => 'phlipper/chef-postgresql'}
cookbook 'python'
cookbook 'rabbitmq'
cookbook 'rabbitmq-management', {:github => 'jdhollis/rabbitmq-management-cookbook'}
cookbook 'redis', {:github => 'ctrabold/chef-redis'}
cookbook 'runit'
cookbook 'sqlite'
cookbook 'sudo'
cookbook 'supervisor'
cookbook 'timezone'
cookbook 'vim'
cookbook 'windows'
cookbook 'yum'
cookbook 'yum-epel'

#future
cookbook 'munin'
