#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'curl'
cookbook 'gae-cookbook', {:github => 'ikame/gae-cookbook.git'}
cookbook 'git'
cookbook 'grunt_cookbook', {:github => 'MattSurabian/grunt_cookbook.git'}
cookbook 'phppgadmin', {:github => 'plexus/chef-phppgadmin'}
cookbook 'memcached'
cookbook 'mongodb'
cookbook 'mysql' 
cookbook 'nginx'
cookbook 'nodejs', {:github => 'mdxp/nodejs-cookbook'}
cookbook 'openssl'
cookbook 'php'
cookbook 'postgresql', {:github => 'phlipper/chef-postgresql'}
cookbook 'python'
cookbook 'redis', {:github => 'ctrabold/chef-redis'}
cookbook 'runit'
cookbook 'sqlite'
cookbook 'sudo'
cookbook 'timezone'
cookbook 'vim'
cookbook 'windows'
cookbook 'yum'
cookbook 'yum-epel'
