#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "bennojoy.nginx"
role "DavidWittman.ansible-redis", github: "DavidWittman/ansible-redis"
role "Ansibles.mysql"
role "Stouts.supervisor"
role "Stouts.users"
